version: "3.9"
services:    
    mysql:
        container_name: mysql
        image: mysql:8.3.0
        restart: always
        env_file: .env
        environment:
            MYSQL_PASSWORD_FILE: /run/secrets/db_password
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
        secrets:
            - db_password
            - db_root_password
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app-network
    nginx:
        container_name: nginx
        image: nginx:stable-alpine3.17
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - wordpress_data:/var/www/html
        networks:
            - app-network
        links:
            - wordpress
    wordpress:
        depends_on:
            - mysql
        container_name: wordpress
        image: wordpress:php8.3-fpm-alpine
        restart: always
        stdin_open: true
        tty: true
        env_file: .env
        environment:
            WORDPRESS_DB_HOST: mysql
        volumes:
            - wordpress_data:/var/www/html
            - ./wordpress:/var/www/html   
        networks:
            - app-network         
    
volumes:
    db_data:
    wordpress_data:

networks:
  app-network:
    driver: bridge

secrets:
    db_password:
        file: ./secrets/db_password.txt
    db_root_password:
        file: ./secrets/db_root_password.txt